# Generated by Django 4.1.5 on 2023-02-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobpost_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='title',
        ),
    ]
